import type { Database } from '@/db/database.types'

type OrgInsert = Database['public']['Tables']['orgs']['Insert']

// The curated org pages, keyed by slug. `bun scripts/seed-orgs.ts` upserts these into public.orgs, writing
// only the fields given here: anything edited by hand in the database and not listed below is left alone.
// Cause and focus come from the lists in utils/org-directory.ts.
// Legal fields were checked on 2026-10-07 against the IRS record (via ProPublica), Companies House, or the org's
// own donate page, and are left out where that didn't settle it: Longview has a UK company and a US 501(c)(3)
// with neither named as primary; Humans First has no record we could tie to it. The state of incorporation
// isn't in those sources, so us_state is unset throughout. Mox runs inside Manifund's own entity. BlueDot has
// a UK company and a US 501(c)(3) with neither named as primary; the IRS has a "Kairos AI Project Inc" that
// nothing on Kairos's site ties to it.
// donation_url is the org's own donation page, or the every.org page its site links to; unset where the site
// links to neither.
export const ORGS: (OrgInsert & { slug: string; name: string })[] = [
  {
    slug: 'metr',
    cause: 'AI safety',
    focus: ['Evals'],
    legal_structure: '501c3',
    legal_name: 'Model Evaluation and Threat Research, Inc.',
    ein: '991219864',
    country: 'US',
    name: 'METR',
    website: 'https://metr.org',
    summary:
      'Builds and runs evaluations that measure whether frontier AI systems can carry out long, autonomous tasks.',
    city: 'Berkeley, CA',
    founded_year: 2022,
    donation_url: 'https://metr.org/donate',
    trace_slug: 'model-evaluation-and-threat-research',
  },
  {
    slug: 'longview',
    cause: 'Philanthropy',
    focus: ['Grantmaking'],
    name: 'Longview',
    website: 'https://www.longview.org',
    summary:
      'Advises major donors and runs funds for reducing risks from AI, nuclear weapons and pandemics.',
    city: 'London',
    founded_year: 2018,
    trace_slug: 'longview-philanthropy',
  },
  {
    slug: 'epoch',
    cause: 'AI safety',
    focus: ['Research'],
    legal_structure: '501c3',
    legal_name: 'Epoch Artificial Intelligence, Inc.',
    ein: '994050541',
    country: 'US',
    name: 'Epoch',
    website: 'https://epoch.ai',
    summary:
      'Researches the trajectory of AI: compute, training data, benchmarks and economic impact.',
    founded_year: 2022,
    trace_slug: 'epoch-ai',
  },
  {
    slug: 'mats',
    cause: 'AI safety',
    focus: ['Field-building'],
    legal_structure: '501c3',
    legal_name: 'MATS Research Inc',
    ein: '990648563',
    country: 'US',
    name: 'MATS',
    website: 'https://www.matsprogram.org',
    summary: 'A research and training program pairing emerging AI safety researchers with mentors.',
    city: 'Berkeley, CA',
    founded_year: 2021,
    trace_slug: 'mats-research',
  },
  {
    slug: 'cais',
    cause: 'AI safety',
    focus: ['Research', 'Field-building'],
    legal_structure: '501c3',
    legal_name: 'Center for Artificial Intelligence Safety Inc',
    ein: '881751310',
    country: 'US',
    name: 'Center for AI Safety',
    website: 'https://safe.ai',
    summary: 'Research, field-building and advocacy to reduce societal-scale risks from AI.',
    city: 'San Francisco, CA',
    founded_year: 2022,
    trace_slug: 'center-for-ai-safety',
  },
  {
    slug: '1day-sooner',
    cause: 'Biosecurity & health',
    focus: ['Policy & advocacy', 'Global health'],
    legal_structure: '501c3',
    legal_name: '1Day Sooner Inc',
    ein: '851103820',
    country: 'US',
    name: '1Day Sooner',
    website: 'https://www.1daysooner.org',
    summary:
      'Advocates for challenge-trial volunteers and for faster development of vaccines and treatments.',
    founded_year: 2020,
    trace_slug: '1day-sooner',
  },
  {
    slug: 'humans-first',
    cause: 'AI safety',
    focus: ['Policy & advocacy'],
    name: 'Humans First',
    trace_slug: 'humans-first',
    hidden: true,
  },
  {
    slug: 'govai',
    cause: 'AI safety',
    focus: ['Research', 'Field-building'],
    legal_structure: '501c3',
    legal_name: 'Centre for the Governance of AI, Inc.',
    ein: '994000294',
    country: 'US',
    name: 'GovAI',
    website: 'https://www.governance.ai',
    summary:
      'Researches how to govern advanced AI, advises governments and labs, and trains people for AI governance careers.',
    city: 'London',
    founded_year: 2016,
    donation_url: 'https://www.every.org/govai#/donate',
    trace_slug: 'centre-for-the-governance-of-ai',
  },
  {
    slug: 'far-ai',
    cause: 'AI safety',
    focus: ['Research', 'Field-building'],
    legal_structure: '501c3',
    legal_name: 'FAR AI Inc',
    ein: '920692207',
    country: 'US',
    name: 'FAR AI',
    website: 'https://far.ai',
    summary:
      'Does technical AI safety research, and runs workshops and a coworking space for the field.',
    city: 'Berkeley, CA',
    founded_year: 2022,
    donation_url: 'https://far.ai/donate',
    trace_slug: 'far-ai',
  },
  {
    slug: 'miri',
    cause: 'AI safety',
    focus: ['Policy & advocacy', 'Research'],
    legal_structure: '501c3',
    legal_name: 'Machine Intelligence Research Institute Inc',
    ein: '582565917',
    country: 'US',
    name: 'MIRI',
    website: 'https://intelligence.org',
    summary:
      'Warns policymakers and the public about the danger of superhuman AI, and researches how to govern it.',
    city: 'Berkeley, CA',
    founded_year: 2000,
    donation_url: 'https://intelligence.org/donate/',
    trace_slug: 'machine-intelligence-research-institute',
  },
  {
    slug: 'iaps',
    cause: 'AI safety',
    focus: ['Policy & advocacy', 'Research'],
    legal_structure: '501c3',
    legal_name: 'Institute for AI Policy and Strategy Inc',
    ein: '320839313',
    country: 'US',
    name: 'IAPS',
    website: 'https://www.iaps.ai',
    summary:
      'A think tank researching policy for advanced AI, with a fellowship for people entering the field.',
    founded_year: 2023,
    trace_slug: 'institute-for-ai-policy-and-strategy',
  },
  {
    slug: 'kairos',
    cause: 'AI safety',
    focus: ['Field-building'],
    name: 'Kairos',
    website: 'https://kairos-project.org',
    summary:
      'Runs programs that bring people into AI safety: SPAR research mentorship, and Pathfinder for university groups.',
    founded_year: 2024,
    trace_slug: 'kairos',
  },
  {
    slug: 'bluedot',
    cause: 'AI safety',
    focus: ['Field-building'],
    name: 'BlueDot',
    website: 'https://bluedot.org',
    summary:
      'Runs courses on AI safety, AI governance and biosecurity, and helps graduates into work on them.',
    founded_year: 2022,
    trace_slug: 'bluedot-impact',
  },
  {
    slug: 'constellation',
    cause: 'AI safety',
    focus: ['Infrastructure', 'Field-building'],
    legal_structure: '501c3',
    legal_name: 'Constellation Institute Inc',
    ein: '932465256',
    country: 'US',
    name: 'Constellation',
    website: 'https://www.constellation.org',
    summary:
      'Runs a research center in Berkeley for people working on AI safety, with fellowships and an incubator.',
    city: 'Berkeley, CA',
    trace_slug: 'constellation',
  },
  {
    slug: 'arc',
    cause: 'AI safety',
    focus: ['Research'],
    legal_structure: '501c3',
    legal_name: 'Alignment Research Center',
    ein: '863605182',
    country: 'US',
    name: 'Alignment Research Center',
    website: 'https://www.alignment.org',
    summary:
      'Theoretical research on aligning future machine learning systems with human interests.',
    city: 'Berkeley, CA',
    founded_year: 2021,
    donation_url: 'https://www.alignment.org/donate/',
    trace_slug: 'alignment-research-center',
  },
  {
    slug: 'redwood',
    cause: 'AI safety',
    focus: ['Research'],
    legal_structure: '501c3',
    legal_name: 'Redwood Research Group Inc',
    ein: '871702255',
    country: 'US',
    name: 'Redwood',
    website: 'https://www.redwoodresearch.org',
    summary:
      'Researches how to stay safe from AI systems that might act against their developers, known as AI control.',
    city: 'Berkeley, CA',
    founded_year: 2021,
    trace_slug: 'redwood-research',
  },
  {
    slug: 'palisade',
    cause: 'AI safety',
    focus: ['Research', 'Policy & advocacy'],
    legal_structure: '501c3',
    legal_name: 'Palisade Research Inc',
    ein: '931591014',
    country: 'US',
    name: 'Palisade',
    website: 'https://palisaderesearch.org',
    summary:
      'Studies what the latest AI systems can do and how they behave, and shows the results to policymakers and the public.',
    founded_year: 2023,
    donation_url: 'https://palisaderesearch.org/donate',
    trace_slug: 'palisade-research',
  },
  {
    slug: 'sage',
    cause: 'AI safety',
    focus: ['Infrastructure'],
    legal_structure: '501c3',
    legal_name: 'Sage Future Inc',
    ein: '881886544',
    country: 'US',
    name: 'Sage',
    website: 'https://sage-future.org',
    summary:
      'Builds interactive explainers and demos of AI (AI Digest, the AI Village) and forecasting tools like Fatebook.',
    donation_url: 'https://www.every.org/sage-future#/donate',
    trace_slug: 'sage',
  },
  {
    slug: 'aifp',
    cause: 'AI safety',
    focus: ['Research'],
    legal_structure: '501c3',
    legal_name: 'AI Futures Project Inc',
    ein: '994320292',
    country: 'US',
    name: 'AI Futures Project',
    website: 'https://www.aifutures.org',
    summary: 'A small research group forecasting the future of AI; the authors of AI 2027.',
    city: 'Berkeley, CA',
    founded_year: 2024,
    donation_url: 'https://www.every.org/ai-futures-project',
    trace_slug: 'ai-futures-project',
  },
  // Already in the table with their own summary and about text: only the links to Trace are added.
  {
    slug: 'lightcone',
    cause: 'AI safety',
    focus: ['Infrastructure'],
    legal_structure: '501c3',
    legal_name: 'Lightcone Infrastructure Inc',
    ein: '920861538',
    country: 'US',
    name: 'Lightcone',
    city: 'Berkeley, CA',
    trace_slug: 'lightcone-infrastructure',
  },
  // Trace has four rows for Forethought; this is the one with most of its grants until they're merged there.
  {
    slug: 'forethought',
    cause: 'AI safety',
    focus: ['Research'],
    legal_structure: 'non_us',
    legal_name: 'Forethought Research',
    country: 'GB',
    name: 'Forethought',
    trace_slug: 'forethought',
  },
  {
    slug: 'mox',
    cause: 'AI safety',
    focus: ['Infrastructure'],
    legal_structure: 'fiscally_sponsored',
    legal_name: 'Manifold for Charity Inc.',
    ein: '883668801',
    country: 'US',
    name: 'Mox',
    city: 'San Francisco, CA',
    trace_slug: 'mox',
  },
  {
    slug: 'tarbell',
    cause: 'AI safety',
    focus: ['Field-building'],
    legal_structure: '501c3',
    legal_name: 'Tarbell Center for AI Journalism Inc',
    ein: '333721895',
    country: 'US',
    name: 'Tarbell',
    trace_slug: 'tarbell-center-for-ai-journalism',
    hidden: true,
  },
  {
    slug: 'transluce',
    cause: 'AI safety',
    focus: ['Research'],
    legal_structure: '501c3',
    legal_name: 'Clarity AI Research Inc.',
    ein: '993262331',
    country: 'US',
    name: 'Transluce',
    trace_slug: 'transluce',
  },
]

// Each org's own projects on Manifund, by project slug: what the org itself raised or is raising for. Projects
// that only mention an org (a MATS scholar's compute grant, an event held at Lighthaven) aren't the org's.
// The org page lists these, and offers donating to the oldest one still open.
export const ORG_PROJECTS: Record<string, string[]> = {
  '1day-sooner': ['create-a-special'],
  aifp: ['ai-forecasting-and-policy-research-by-the-ai-2027-team'],
  cais: ['ai-safety--society'],
  epoch: [
    'pilot-for-new-benchmark-by-epoch-ai',
    'investigating-and-informing-the-public-about-the-trajectory-of-ai',
  ],
  forethought: ['forethought'],
  iaps: ['ai-policy-work--iaps'],
  lightcone: ['lightcone-infrastructure'],
  mats: ['mats-funding'],
  mox: ['mox-2026-fundraiser', 'mox-a-coworking--events-space-in-sf'],
  sage: ['ai-digest', 'fatebook-and-quantified-intuitions'],
  tarbell: ['tarbell-center-for-ai-journalism'],
  transluce: ['transluce-fund-scalable-democratic-oversight-of-ai'],
}
